# Generated by Django 5.1.1 on 2024-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
