# Generated by Django 5.1.1 on 2024-09-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccount", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
