import type { Metadata } from "next";
import "./globals.css";
import { NavBar, Footer } from "@/components";
import AddRentInfoModal from "@/components/modals/AddRentInfoModal";
import UpdateRentInfoModal from "@/components/modals/UpdateRentInfo";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
        <AddRentInfoModal/>
        <UpdateRentInfoModal/>
        <Footer/>
      </body>
    </html>
  );
}
