import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components";
import Footer from "@/components/Footer";
import AddRentInfoModal from "@/components/modals/AddRentInfoModal";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto relative">
        <NavBar/>
        {children}
        <AddRentInfoModal/>
        <Footer/>
      </body>
    </html>
  );
}
