# Generated by Django 5.1.1 on 2024-10-11 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                (
                    "main_img",
                    models.ImageField(
                        default="backend/media/uploads/homes/dummy-home.jpg",
                        upload_to="uploads/cars",
                    ),
                ),
                ("brand_logo", models.ImageField(upload_to="uploads/cars/logo")),
                ("description", models.TextField()),
                ("model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=255)),
                ("passengers", models.IntegerField()),
                ("suitcases", models.IntegerField()),
                (
                    "gas_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "Gasoline"),
                            ("diesel", "Diesel"),
                            ("electricity", "Electricity"),
                            ("natural gas", "Natural Gas"),
                        ],
                        max_length=100,
                    ),
                ),
                ("price_per_day", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("renting", "Renting"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "main_img",
                    models.ImageField(
                        default="backend/media/uploads/homes/dummy-home.jpg",
                        upload_to="uploads/homes",
                    ),
                ),
                ("description", models.TextField()),
                ("price_per_month", models.IntegerField()),
                ("address", models.TextField()),
                ("built_at", models.DateField()),
                ("bedrooms", models.PositiveIntegerField(default=1)),
                ("bathrooms", models.PositiveIntegerField(default=1)),
                ("living_areas", models.PositiveIntegerField()),
                ("kitchen", models.BooleanField(default=True)),
                ("laundry", models.BooleanField(default=False)),
                ("heating", models.BooleanField(default=False)),
                ("cooling", models.BooleanField(default=False)),
                ("water_supply", models.BooleanField(default=True)),
                ("internet_access", models.BooleanField(default=True)),
                ("electricity", models.BooleanField(default=True)),
                ("security_system", models.BooleanField(default=False)),
                ("smoke_detector", models.BooleanField(default=False)),
                ("yard", models.BooleanField(default=False)),
                ("parking_space", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CarGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/cars")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="rentals.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/homes")),
                (
                    "homes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="rentals.homes",
                    ),
                ),
            ],
        ),
    ]
