# Generated by Django 5.1.1 on 2024-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="homes",
        ),
        migrations.DeleteModel(
            name="Homes",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
