# Generated by Django 5.0.3 on 2024-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homes",
            name="main_img",
            field=models.ImageField(
                default="backend/media/uploads/homes/dummy-home.jpg",
                upload_to="uploads/homes",
            ),
        ),
    ]
