# Generated by Django 5.1.1 on 2024-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0002_remove_image_homes_delete_homes_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
