# Generated by Django 5.1.1 on 2024-10-26 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
