# Generated by Django 5.1.1 on 2024-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0005_renter_reservation_payment_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renter",
            name="license_photo",
            field=models.ImageField(upload_to="uploads/license"),
        ),
    ]
