# Generated by Django 5.1.1 on 2024-11-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0008_alter_reservation_renter"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="total_date",
            field=models.IntegerField(default=1),
        ),
    ]
