# Generated by Django 5.1.1 on 2024-11-02 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0009_reservation_total_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
    ]
