# Generated by Django 5.1.1 on 2024-11-16 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0010_remove_reservation_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
