# Generated by Django 5.1.1 on 2025-01-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0013_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("answers", models.TextField()),
            ],
        ),
    ]
