# Generated by Django 5.1.1 on 2024-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="avatar",
            field=models.ImageField(
                default="uploads/avatars/default-avatar.png",
                upload_to="uploads/avatars",
            ),
        ),
    ]
